---
blank_issues_enabled: false
contact_links:
  - name: Vellum Community Support
    url: https://github.com/XxX-Daniil-underscore-Zaikin-XxX/PapyrusDefaultProject/discussions
    about: Please ask and answer questions here.
